"""Builders for the replay-profile property tests (test-only, pure, offline).

The four ``replay``-profile property tests (P12, P13, P15, P17) drive the
:class:`~simulator.engine.ReplayEngine` end to end through a :class:`FakeSink`
and a :class:`TruthStore` in a temp directory (ADR-4, R20.7). They need two kinds
of input:

- **Small scenarios** (<=20 DTs, <=2 simulated hours) generated by Hypothesis so
  50 examples stay fast (ADR-4). :func:`small_flood_scenario` builds a structurally
  valid Scenario whose damage script may include a *flood-cause* trip on a DT that
  is placed **inside** an active Flood_Polygon, and :func:`small_grid_view` builds
  a matching :class:`GridView` where that DT's point lies in the flood polygon so
  the flood-cause geometry rule (R10.4) actually holds.
- **The full ``michaung-style`` scenario** for the single ``@example`` each test
  carries (R20.7). :func:`build_michaung_grid_view` reconstructs a real
  :class:`GridView` for that scenario by mirroring ``simulator.grid.build``'s
  assembly (topology + geometry via the geometry module), then guarantees the
  scenario's two flood-cause devices (``sub_004`` and ``dt_009``, per the shipped
  ``michaung-style`` damage script and task 5.4 "a substation inside the flood
  polygon") are sited inside the active Flood_Polygon so the flood-cause safety
  properties are meaningful on the real geometry.

Not product code: these live under ``tests/`` only and import nothing from
``boto3``/``botocore``. They read no wall clock, PID or network — the parent
``tests/conftest.py`` blocks sockets and freezes time.
"""

from __future__ import annotations

import random
from dataclasses import dataclass
from datetime import UTC, datetime, timedelta
from pathlib import Path

from shapely.geometry import Point, Polygon  # type: ignore[import-untyped]

from simulator.generation.grid_view import GridView, LonLat
from simulator.grid import geometry as geometry_mod
from simulator.grid.topology import GridTopology, build_forest
from simulator.scenario import loader as loader_mod
from simulator.scenario.loader import load_scenario
from simulator.scenario.model import (
    Bbox,
    CrewDepot,
    CrewSpec,
    DamageEntry,
    FloodPolygon,
    FloodStatusChange,
    GridCounts,
    Phase,
    Scenario,
    SourceCredit,
    TrackPoint,
    ValidityWindow,
)
from simulator.scenario.weather import WeatherSnapshot

# --------------------------------------------------------------------------
# Small scenarios for the generated (50-example) replay cases.
# --------------------------------------------------------------------------

# A small study bbox (Chennai-ish), away from the antimeridian/poles.
_SMALL_BBOX = Bbox(min_lon=80.0, min_lat=12.9, max_lon=80.2, max_lat=13.1)

# Anchor times: a 2-simulated-hour window keeps 50 examples fast (ADR-4).
_SMALL_START = datetime(2023, 12, 5, 0, 0, tzinfo=UTC)
_SMALL_END = datetime(2023, 12, 5, 2, 0, tzinfo=UTC)

# The active Flood_Polygon for a small scenario: a square in one corner of the
# bbox, active for the whole window. Any DT sited inside it can carry cause flood.
_FLOOD_MIN_LON = 80.02
_FLOOD_MIN_LAT = 12.92
_FLOOD_MAX_LON = 80.06
_FLOOD_MAX_LAT = 12.96

_FLOOD_RING: list[LonLat] = [
    (_FLOOD_MIN_LON, _FLOOD_MIN_LAT),
    (_FLOOD_MAX_LON, _FLOOD_MIN_LAT),
    (_FLOOD_MAX_LON, _FLOOD_MAX_LAT),
    (_FLOOD_MIN_LON, _FLOOD_MAX_LAT),
    (_FLOOD_MIN_LON, _FLOOD_MIN_LAT),
]

# A point comfortably inside the flood polygon (used for flood-cause DTs/meters).
_FLOOD_INTERIOR: LonLat = (
    round((_FLOOD_MIN_LON + _FLOOD_MAX_LON) / 2, 6),
    round((_FLOOD_MIN_LAT + _FLOOD_MAX_LAT) / 2, 6),
)

# A point well away from the flood polygon (used for non-flood DTs).
_DRY_BASE_LON = 80.14
_DRY_BASE_LAT = 13.04

_SERVICE_HALF_SIDE = 0.002  # ~200 m square Service_Area around each DT point.


@dataclass(frozen=True, slots=True)
class SmallReplayInputs:
    """The inputs one small replay example needs to drive the engine."""

    scenario: Scenario
    weather: WeatherSnapshot
    grid: GridView
    content_hash: str


def _dry_point(index: int) -> LonLat:
    """Return a distinct ``[lon, lat]`` point outside the flood polygon."""
    lon = round(_DRY_BASE_LON + 0.003 * (index + 1), 6)
    lat = round(_DRY_BASE_LAT + 0.003 * (index + 1), 6)
    return (lon, lat)


def _square_ring(centre: LonLat) -> list[LonLat]:
    """Return a small closed square ring (right-hand rule) around ``centre``."""
    lon, lat = centre
    half = _SERVICE_HALF_SIDE
    return [
        (round(lon - half, 6), round(lat - half, 6)),
        (round(lon + half, 6), round(lat - half, 6)),
        (round(lon + half, 6), round(lat + half, 6)),
        (round(lon - half, 6), round(lat + half, 6)),
        (round(lon - half, 6), round(lat - half, 6)),
    ]


def _small_flood_polygon() -> FloodPolygon:
    """Return the small scenario's Flood_Polygon: active over the whole window."""
    return FloodPolygon(
        id="FP-1",
        geometry=[list(_FLOOD_RING)],
        validity=ValidityWindow(start=_SMALL_START, end=_SMALL_END),
        status_changes=[FloodStatusChange(status="active", sim_time=_SMALL_START)],
    )


def _small_phases() -> list[Phase]:
    """Return four contiguous named phases spanning the small window."""
    quarter = (_SMALL_END - _SMALL_START) / 4
    names = ("approach", "peak_wind", "flooding", "recession")
    return [
        Phase(
            name=name,  # type: ignore[arg-type]
            start=_SMALL_START + quarter * i,
            end=_SMALL_START + quarter * (i + 1),
        )
        for i, name in enumerate(names)
    ]


def small_grid_view(dt_count: int, *, flood_dt_index: int | None) -> GridView:
    """Build a tiny GridView with ``dt_count`` DTs; one DT may sit in the flood.

    A single Substation and Feeder root ``dt_count`` Laterals and DTs. Every DT is
    given a distinct interior point and a square Service_Area around it. When
    ``flood_dt_index`` is not ``None``, that DT's point (and Service_Area) is placed
    inside the active Flood_Polygon so a flood-cause trip on it satisfies R10.4.

    Args:
        dt_count: Number of DTs (>= 1) to place.
        flood_dt_index: Index of the DT to site inside the flood, or ``None`` for
            an all-dry grid.

    Returns:
        A :class:`GridView` over the built topology and placed geometry.
    """
    counts = GridCounts(
        substations=1, feeders=1, laterals=dt_count, dts=dt_count,
        customer_min=1, customer_max=100,
    )
    topology: GridTopology = build_forest(counts, random.Random(0))  # noqa: S311

    sub_id = topology.devices_of_type("Substation")[0].id
    substation_points: dict[str, LonLat] = {sub_id: _dry_point(-1)}

    line_coords: dict[str, list[LonLat]] = {}
    for line in (*topology.devices_of_type("Feeder"), *topology.devices_of_type("Lateral")):
        line_coords[line.id] = [_dry_point(-1), _dry_point(0)]

    dt_points: dict[str, LonLat] = {}
    service_area_rings: dict[str, list[list[LonLat]]] = {}
    for index, dt in enumerate(topology.devices_of_type("DT")):
        point = _FLOOD_INTERIOR if index == flood_dt_index else _dry_point(index)
        dt_points[dt.id] = point
        service_area_rings[dt.id] = [_square_ring(point)]

    return GridView(
        topology=topology,
        substation_points=substation_points,
        line_coords=line_coords,
        dt_points=dt_points,
        service_area_rings=service_area_rings,
    )


def _small_weather() -> WeatherSnapshot:
    """Return a minimal Weather_Snapshot covering the small window (two records)."""
    return WeatherSnapshot.model_validate(
        {
            "records": [
                {
                    "record_time": _SMALL_START.isoformat(),
                    "centre": (80.1, 13.0),
                    "wind_kmh": 40.0,
                    "gust_kmh": 55.0,
                    "rain_mm_h": 5.0,
                    "pressure_hpa": 1000.0,
                },
                {
                    "record_time": _SMALL_END.isoformat(),
                    "centre": (80.1, 13.0),
                    "wind_kmh": 30.0,
                    "gust_kmh": 45.0,
                    "rain_mm_h": 3.0,
                    "pressure_hpa": 1005.0,
                },
            ]
        }
    )


def small_flood_scenario(
    *,
    dt_count: int,
    flood_dt_index: int | None,
    trip_offset_minutes: int,
    scenario_id: str = "test-replay",
) -> Scenario:
    """Build a small, structurally valid Scenario with an optional flood-cause trip.

    When ``flood_dt_index`` is not ``None`` a single ``flood``-cause :class:`DamageEntry`
    is scripted on that DT at ``trip_offset_minutes`` after the flood becomes active;
    the matching :func:`small_grid_view` places that DT inside the flood polygon so
    the trip is genuinely flood-caused (R10.4). With ``None`` the damage script is
    empty (an all-dry grid, no flood-cause trip).

    Args:
        dt_count: Number of DTs (1..20 to keep examples small, ADR-4).
        flood_dt_index: The DT index scripted to trip on ``flood``, or ``None``.
        trip_offset_minutes: Minutes after ``sim_start`` the flood trip occurs.
        scenario_id: The scenario id (any fixed value for a built scenario).

    Returns:
        The small :class:`Scenario`.
    """
    damage: list[DamageEntry] = []
    if flood_dt_index is not None:
        dt_id = _dt_id_for_index(dt_count, flood_dt_index)
        trip_time = _SMALL_START + timedelta(minutes=trip_offset_minutes)
        damage.append(DamageEntry(device_id=dt_id, sim_time=trip_time, cause="flood"))

    crew = CrewDepot(
        crew_id="crew-1",
        depot=(_SMALL_BBOX.max_lon - 0.01, _SMALL_BBOX.max_lat - 0.01),
        member_ids=["m-a", "m-b"],
        skills=["line"],
    )
    return Scenario(
        scenario_id=scenario_id,
        version="1.0.0",
        study_area_bbox=_SMALL_BBOX,
        sim_start=_SMALL_START,
        sim_end=_SMALL_END,
        phases=_small_phases(),
        cyclone_track=[
            TrackPoint(sim_time=_SMALL_START, centre=(80.1, 13.0)),
            TrackPoint(sim_time=_SMALL_END, centre=(80.1, 13.02)),
        ],
        weather_snapshot_ref="weather_snapshot.json",
        flood_polygons=[_small_flood_polygon()],
        damage_script=damage,
        citizen_reports=[],
        grid_spec=GridCounts(
            substations=1, feeders=1, laterals=dt_count, dts=dt_count,
            customer_min=1, customer_max=100,
        ),
        facility_tag_map={},
        crew_spec=CrewSpec(skills=["line"], depots=[crew], expected_crew_count=1),
        default_seed=0,
        noise_rate_per_hour=None,
        wind_damage_threshold_kmh=90.0,
        sources=[SourceCredit(title="t", licence="ODbL", citation="c")],
    )


def _dt_id_for_index(dt_count: int, index: int) -> str:
    """Return the DT id at ``index`` for a ``dt_count``-DT grid (mirrors topology)."""
    topology = build_forest(
        GridCounts(
            substations=1, feeders=1, laterals=dt_count, dts=dt_count,
            customer_min=1, customer_max=100,
        ),
        random.Random(0),  # noqa: S311
    )
    return topology.devices_of_type("DT")[index].id


def small_inputs(
    *,
    dt_count: int,
    flood_dt_index: int | None,
    trip_offset_minutes: int,
) -> SmallReplayInputs:
    """Assemble the scenario, weather and matching grid for one small example."""
    scenario = small_flood_scenario(
        dt_count=dt_count,
        flood_dt_index=flood_dt_index,
        trip_offset_minutes=trip_offset_minutes,
    )
    grid = small_grid_view(dt_count, flood_dt_index=flood_dt_index)
    return SmallReplayInputs(
        scenario=scenario, weather=_small_weather(), grid=grid, content_hash="test-hash",
    )


# --------------------------------------------------------------------------
# The full michaung-style scenario for the single @example each test carries.
# --------------------------------------------------------------------------

_MICHAUNG_ID = "michaung-style"

#: The shipped michaung damage script's flood-cause devices (task 5.4: a
#: substation inside the flood polygon). These must be sited inside the active
#: Flood_Polygon so P12/P13 are meaningful on the real geometry. They match the
#: scenario's flood-cause damage entries (a Substation and a DT inside FP-1).
_MICHAUNG_FLOOD_DEVICES = ("sub_004", "dt_009")


@dataclass(frozen=True, slots=True)
class MichaungInputs:
    """The inputs the full michaung ``@example`` needs to drive the engine."""

    scenario: Scenario
    weather: WeatherSnapshot
    grid: GridView
    content_hash: str


def _michaung_scenario_dir() -> Path:
    """Return the michaung scenario directory path (mirrors the loader's resolution)."""
    return loader_mod._SCENARIOS_DIR / _MICHAUNG_ID


def load_michaung_weather() -> WeatherSnapshot:
    """Load the committed michaung Weather_Snapshot into a :class:`WeatherSnapshot`."""
    path = _michaung_scenario_dir() / "weather_snapshot.json"
    return WeatherSnapshot.model_validate_json(path.read_bytes())


def _flood_interior_point(scenario: Scenario) -> LonLat:
    """Return a point inside the first Flood_Polygon of ``scenario`` (6-dp rounded)."""
    ring = scenario.flood_polygons[0].geometry[0]
    polygon = Polygon(ring)
    interior: Point = polygon.representative_point()
    return (round(interior.x, 6), round(interior.y, 6))


def build_michaung_grid_view() -> GridView:
    """Reconstruct a real :class:`GridView` for the ``michaung-style`` scenario.

    Mirrors ``simulator.grid.build``'s assembly without touching the OSM extract:
    the radial forest comes from :func:`build_forest`, and geometry (substation
    points, feeder/lateral lines, DT points and Voronoi Service_Areas) from the
    pure :mod:`simulator.grid.geometry` module, seeded deterministically from the
    scenario's default seed. The two scripted flood-cause devices are then sited
    inside the active Flood_Polygon so the flood-cause safety properties hold on
    real geometry (task 5.4).

    Returns:
        A :class:`GridView` over the michaung topology and placed geometry.
    """
    scenario, _ = load_scenario(_MICHAUNG_ID)
    bbox = scenario.study_area_bbox
    rng = random.Random(scenario.default_seed)  # noqa: S311 -- deterministic replay seeding

    topology = build_forest(scenario.grid_spec, rng)

    subs = topology.devices_of_type("Substation")
    sub_pts = geometry_mod.place_points(len(subs), bbox, rng)
    substation_points = {sub.id: pt for sub, pt in zip(subs, sub_pts, strict=True)}

    line_coords: dict[str, list[LonLat]] = {}
    for line in (*topology.devices_of_type("Feeder"), *topology.devices_of_type("Lateral")):
        line_coords[line.id] = geometry_mod.place_line(bbox, rng)

    dts = topology.devices_of_type("DT")
    dt_point_list = geometry_mod.place_points(len(dts), bbox, rng)
    dt_points = {dt.id: pt for dt, pt in zip(dts, dt_point_list, strict=True)}
    rings = geometry_mod.service_areas(dt_point_list, bbox)
    service_area_rings = {dt.id: ring for dt, ring in zip(dts, rings, strict=True)}

    # Site the scripted flood-cause devices inside the active Flood_Polygon so the
    # flood-cause geometry rule (R10.4) holds for them on real geometry.
    flood_point = _flood_interior_point(scenario)
    for device_id in _MICHAUNG_FLOOD_DEVICES:
        if device_id in substation_points:
            substation_points[device_id] = flood_point
        if device_id in dt_points:
            dt_points[device_id] = flood_point
            service_area_rings[device_id] = [_square_ring(flood_point)]

    return GridView(
        topology=topology,
        substation_points=substation_points,
        line_coords=line_coords,
        dt_points=dt_points,
        service_area_rings=service_area_rings,
    )


def michaung_inputs() -> MichaungInputs:
    """Assemble the full michaung scenario, weather and reconstructed grid."""
    scenario, content_hash = load_scenario(_MICHAUNG_ID)
    return MichaungInputs(
        scenario=scenario,
        weather=load_michaung_weather(),
        grid=build_michaung_grid_view(),
        content_hash=str(content_hash),
    )
